mysite/blog_app/urls.py
from django.urls import path
from blog_app import views

app_name = "blog_app"
urlpatterns = [
    path("about/", views.AboutView.as_view(), name = "about"),
    path("", views.PostListView.as_view(), name = "post_list"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name = "post_detail"),
    path("post/new/", views.CreatePostView.as_view(), name = "post_new"),
    path("post/<int:pk>/edit/", views.PostUpdateView.as_view(), name = "post_edit" ),
    path("post/<int:pk>/remove/", views.PostDeleteView.as_view(), name = "post_remove"),
    path("drafts/", views.DraftListView.as_view(), name = "post_draft_list"),
    path("post/<int:pk>/comment/", views.add_comment_to_post, name = "add_comment_to_post"),
    path("comment/<int:pk>/approve/", views.comment_approve, name = "comment_approve"),
    path("comment/<int:pk>/remove/",views.comment_remove, name = "comment_remove"),
    path("post/<int:pk>/publish/", views.post_publish, name = "post_publish")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog_app.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name = "login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(next_page = "/"), name = "logout")
]

mysite/blog_app/models.py
from django.db import models
from django.utils import timezone 
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    title = models.CharField(max_length = 255)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comments = True)

    def get_absolute_url(self):
        return reverse("blog_app:post_detail", kwargs = {'pk' : self.pk })    

    def __str__(self):  
        return self.title       


class Comment(models.Model):
    post = models.ForeignKey('blog_app.Post' , related_name = 'comments', on_delete = models.CASCADE)
    author = models.CharField(max_length = 255)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    approved_comments = models.BooleanField(default = False)

    def approve(self):
        self.approved_comments = True
        self.save()
    
    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text    

mysite/blog_app/forms.py
from django import forms
from blog_app.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author', 'title','text')

        widget = {
            'title' : forms.TextInput(attrs = {'class' : 'textinputclasss'}),
            'text' : forms.Textarea(attrs = {'class' : 'editable medium-editor-textarea postcontent'})

        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('author','text')

        widget = {
            'author' : forms.TextInput(attrs = {'class' : 'textinputclass'}),
            'text' : forms.Textarea(attrs = {'class' : 'editable medium-editor-textarea'})
        }

mysite/blog_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from blog_app.models import Post, Comment
from blog_app.forms import PostForm, CommentForm
from django.views.generic import (TemplateView, ListView,
                                    DetailView, CreateView,
                                    UpdateView, DeleteView )
# Create your views here.


class AboutView(TemplateView):
    template_name = 'blog_app/about.html'

class PostListView(ListView):
    model = Post
    
    def get_queryset(self):
        # __lte = lessthen or equal
        return Post.objects.filter(published_date__lte = timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = "/login/"
    redirect_field_name = "blog_app/post_detail.html"
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/login/"
    redirect_field_name = "blog_app/post_detial.html"
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blog_app:post_list") 


class DraftListView(LoginRequiredMixin, ListView):
    login_url = "/login/"
    redirect_field_name = "blog_app/post_list.html"
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull = True).order_by('create_date')




###################################################################################################################
###################################################################################################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk = pk)
    post.publish()
    return redirect("blog_app:post_detail", pk = pk)


    
@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk = pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect("blog_app:post_detail", pk = post.pk)
    else:
        form = CommentForm()

    return render(request, 'blog_app/comment_form.html', {'form' : form})        

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk = pk)
    comment.approve()
    return redirect('blog_app:post_detail', pk = comment.post.pk)     


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk = pk) #fetch the "comment" object from the database using primary key (pk) provided in the url

    #if request.user != comment.author and request.user != comment.post.author:  #it is accessible by post_user and comment_user to delete...
    # if request.user != comment.author:
    #     return HttpResponseForbidden("You are not allowed to delete this  comment.")

    post_pk = comment.post.pk #save the key in seperate veriable
    comment.delete()
    return redirect("blog_app:post_detail", pk = post_pk)

mysite/blog_app/templates/blog_app/about.html
{% extends "blog_app/base.html" %}

{% block content %}
    

    <h1> About this Company</h1>
    <p> Thanks for checking it out..!</p>

{% endblock %}

mysite/blog_app/templates/blog_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>BLOG</title>

  <!-- Bootstrap 5 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" />

  <!-- Medium Editor -->
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" />

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/blog_app.css' %}" />

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet" />

  <!-- for enhance the myblog tag -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet" />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">


</head>

<body class="loader">
  <!-- Navbar -->
  <!-- ✅ Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark custom-navbar techfont">
    <div class="container-fluid">
    <!-- Logo -->
    <a class="navbar-brand d-flex align-items-center" href="{% url 'blog_app:post_list' %}">
      <img src="{% static 'images/logo2.png' %}" alt="myblog logo" height="50" class="me-2">
      
    </a>

    <!-- Toggle for mobile -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Nav links -->
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
      <!-- Left side links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog_app:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.github.com" target="_blank">Github</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.linkedin.com" target="_blank">LinkedIn</a>
        </li>
      </ul>

      <!-- Right side links -->
      <ul class="navbar-nav align-items-center">
        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog_app:post_new' %}">New Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog_app:post_draft_list' %}">Drafts</a>
            </li>
            <li class="nav-item">
              <form method="post" action="{% url 'logout' %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-link nav-link" style="padding: 0; border: none; background: none;">
                    <i class="fas fa-sign-out-alt"></i> Logout
                  </button>
              </form>
            </li>
        <!-- <li class="nav-item">
          <span class="navbar-text">
            <i class="fas fa-user"></i>{{ user.username }}
          </span>
        </li> -->
        {% else %}
        <!-- <i class="fas fa-user fa-2x"></i> Login -->
        <span class="navbar-text">
            <a href = "{% url 'login' %}"><i class="fas fa-user"></i> <b>Login</b></a>
          </span>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


  <!-- Content block -->
  <div class="container my-4">
    <div class="row">
      <div class="col-md-8 blog_posts">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>

  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mysite/blog_app/templates/blog_app/comment_form.html
{% extends "blog_app/base.html" %}

{% block content %}
    <h1>New Comment </h1>
    <form class = "post-form" method = "POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = "submit" class = 'save btn btn-secondary'>Post Comment</button>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock%}

mysite/blog_app/templates/blog_app/post_confirm_delete.html
{% extends "blog_app/base.html" %}

{% block content %}
    <form method = "POST">
        {% csrf_token %}
        <p> Are you sure want to delete {{ object }}</p>
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="{% url 'blog_app:post_detail' object.pk %}" class="btn btn-secondary">Cancel</a>
        
    </form>
{% endblock%}

mysite/blog_app/templates/blog_app/post_detail.html
{% extends "blog_app/base.html" %}

{% block content %}
    <h1 class = "posttitle loader"> {{ post.title }} </h1>  
    {% if post.published_date %}
        <div class = "date postdate">
            {{ post.published_date}}
        </div>
    {% else %}
        <a class = "btn btn-secondary" href = "{% url 'blog_app:post_publish' post.pk %}"> Publish </a>
    {% endif %}  
    <p class='postcontent'>
        <strong>{{ post.title|escape }}</strong><br>
        {{ post.text|safe|linebreaksbr }}
    </p>

    {% if user.is_authenticated %}
    <a class = "btn btn-primary" href = "{% url 'blog_app:post_edit'  post.pk %}">
        <span class = "glyphicon glyphicon-pencil">edit</span>
    </a>
    <a class = "btn btn-primary" href = "{% url 'blog_app:post_remove' post.pk %}">
        <span class = "glyphicon glyphicon-remove">Delete</span>
    </a>
    {% endif %}    

    <hr>

    <a class = "btn btn-primary btn-comment" href = "{% url 'blog_app:add_comment_to_post' post.pk %}"> Add Comment </a>

    <div class = "container">
        {% for comment in post.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approved_comment %}
                {{ comment.create_date }}
                {% if not comment.approved_comment %}
                    <a class = "btn btn-secondary" href = "{% url 'blog_app:comment_remove'  comment.pk %}">
                        <span class = "glyphicon glyphicon-remove">delete</span>
                    </a>

                    <a class = "btn btn-info" href = "{% url 'blog_app:comment_approve' comment.pk %}">
                        <span class = "glyphicon glyphicon-ok">post comment</span>
                    </a>
                {% endif %}

                <p> {{ comment.text|safe|linebreaksbr }}</p>
                <p> Posted By : {{ comment.author }} </p>
            {% endif %} 
            
            {% empty %}
                <p> No comments </p>
        {% endfor %}
    </div>
{% endblock%}

mysite/blog_app/templates/blog_app/post_draft_list.html
{% extends "blog_app/base.html" %}

{% block content %}
    {% for post in posts %}
    <div class = "post">
        <p class = "date"> created : {{ post.create_date|date: 'd-m-y' }}</p>
        <h1><a href = "{% url 'post_detail' pk = post.pk %}">{{post.title}}</a></h1>
        <p>{{post.text|turncatechars:200}}</p>
    </div>
    {% endfor %}
{% endblock%}

mysite/blog_app/templates/blog_app/post_form.html
{% extends "blog_app/base.html" %}

{% block content %}
    <h1> New Post </h1>
    <form class = "post-form" method = "POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = "submit" class = "save btn btn-secondary" name = "button"> save </button>
    </form>

    <script>var editor = new MediumEditor('.editable'); </script>   

    
{% endblock%}

mysite/blog_app/templates/blog_app/post_list.html
{% extends "blog_app/base.html" %}

{% block content %}
    <div class = "centerstage">
        {% for post in post_list %}
            <div class = "post">
                <h1><a href = "{%url 'blog_app:post_detail' post.pk %}">{{ post.title }}</a></h1>
                <div class = "date">
                    <p>Published on : {{ post.published_date|date:"D M Y"}}</p>
                </div>
                <a href = "{% url 'blog_app:post_detail' post.pk %}">Comments : {{post.approve_comments.count }}</a>
            </div>
        {% endfor %}
        
    </div>
{% endblock%}